#!/usr/bin/env bash
#Main variables
ERMSG='\e[01;31mError occured:\e[0m'
DATE=$(date +%d-%m-%Y-%H:%M:%S)
SNAP=''  #snapshot's location dir
LOC=''   #data location dir
MLOG='~/main.log'  #main log location
ERLOG='~/error.log' #error log location
MAIL=''  #mail for notification purposes
#check if rdiff-backup is installed & if dir's are exist
checking() {
        which rdiff-backup 1> /dev/null && 
        if [ ! -d $SNAP ]; then echo -e "$ERMSG snapshots directory $SNAP doesn't exist." &&
                                echo -e "$DATE $ERMSG snapshots directory $SNAP doesn't exist." >> $ERLOG && error_report;
        else
            if [ ! -d $LOC ]; then echo -e "$ERMSG data location directory $LOC doesn't exist." && 
                                   echo -e "$DATE $ERMSG data location directory $LOC doesn't exist." >> $ERLOG && error_report
            else prepare
                fi
        fi || echo -e "$ERMSG rdiff-backup is missing, to make this stuff working u need to install it." &&
              echo -e "$ERMSG rdiff-backup is missing, to make this stuff working u need to install it."  >> $ERLOG && error_report
}
error_report() {
       echo "Backup process was failed at $DATE" | mail -s "Something is not good with backup system" $MAIL; exit 1
}
prepare() {
        find $LOC -mindepth 1 -maxdepth 1 -type d | sed "s#$LOC##g" | while read -r dirs
                                                                       do [ -d "$SNAP$dirs.back" ] || mkdir "$SNAP$dirs.back"
                                                                      done
make_snapshot
}
make_snapshot() {
find $LOC -mindepth 1 -maxdepth 1 -type d | sed "s#$LOC##g" | while read -r locaton; do rdiff-backup "$LOC$locaton" "$SNAP$locaton.back"; 
                                                              done
echo "Snapshots was created successfully at $DATE" >> $MLOG && exit 0 || echo "$ERMSG at $DATE can't create all snapshots." >> $ERLOG && error_report; exit 1
}
checking
