#!/usr/bin/env bash
#dependies: mysqldump
#DO NOT RUN AS ROOT 
DATE=$(date +%d-%m-%Y-%H:%M:%S)
MAIL='' #mail for notification
MLOG=''  #main log location
ERLOG='' #error log location
CNF='' #config for mysql
BDIR='' #backup dir
backup() {
 mysqldump --defaults-extra-file=$CNF --all-databases | gzip -c > $BDIR$DATE.dump.sql.gz && echo "mysql backup was succesfully done at $DATE" >> $MLOG && 
  removeold || echo "Backup process was failed at $DATE" | mail -s "Something is not good with backup system (mysql backup failed)" $MAIL && 
   echo "mysql backup was failed at $DATE" >> $ERLOG; exit 1
}
removeold() {
   find $BDIR -type f -iname '*.sql.gz' -mtime +60 -exec rm -f {} \; && exit 0
}
backup

